### ISSUE TITLE
Wild Rift crash on login select

### ISSUE THREAD

**Issue by Gaboros** [sebanc/brunch#1820]
Brunch version: r110 stable 20230305
ChromeOS Image: Zork
Laptop: Asus VivoBook Ryzen 5 4300U
Kernel: 5.15 or 6.1

When I click on any login method in Wild Rift the app closes.

**Comment by Gaboros** [comment]
04-08 15:08:48.187  4554  4948 W System.err: javax.net.ssl.SSLPeerUnverifiedException: Hostname astat.bugly.cros.wr.pvp.net not verified:
04-08 15:08:48.187  4554  4948 W System.err:     certificate: sha1/QyGXHW+muBgFWxBQ+NC1eyLkTKA=
04-08 15:08:48.187  4554  4948 W System.err:     DN: C=US,ST=California,L=Los Angeles,O=Riot Games Inc,CN=android.bugly.wr.pvp.net
04-08 15:08:48.187  4554  4948 W System.err:     subjectAltNames: [android.bugly.wr.pvp.net, bugly.prod01.amer.cros.wr.pvp.net, api.bugly.prod01.amer.cros.wr.pvp.net, cas.bugly.prod01.amer.cros.wr.pvp.net, ios.bugly.prod01.amer.cros.wr.pvp.net, android.bugly.prod01.amer.cros.wr.pvp.net]
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
04-08 15:08:48.187  4554  4948 W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
04-08 15:08:48.187  4554  4948 W System.err:    at com.uqm.crashsight.proguard.g.a(:272)
04-08 15:08:48.187  4554  4948 W System.err:    at com.uqm.crashsight.proguard.g.a(:121)
04-08 15:08:48.187  4554  4948 W System.err:    at com.uqm.crashsight.proguard.j.run(:329)
04-08 15:08:48.187  4554  4948 W System.err:    at java.lang.Thread.run(Thread.java:923)
04-08 15:08:48.414  4522  4537 I Finsky:quick_launch: [39] mst.run(21): Stats for Executor: bgExecutor ncj@5a4c409[Running, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
04-08 15:08:48.451  4554  4560 E CRASH   : signal 11 (SIGSEGV), code 0 (?), fault addr 0000275e000011ca
04-08 15:08:48.451  4554  4560 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 15:08:48.451  4554  4560 E CRASH   : Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
04-08 15:08:48.451  4554  4560 E CRASH   : Build fingerprint: 'google/zork/zork_cheets:11/R112-15359.45.0/9844704:user/release-keys'
04-08 15:08:48.451  4554  4560 E CRASH   : Revision: '0'
04-08 15:08:48.451  4554  4560 E CRASH   : pid: 4554, tid: 4560, name: Signal Catcher  >>> com.riotgames.league.wildrift <<<
04-08 15:08:48.451  4554  4560 E CRASH   :     x0   0000000000000000  x1   0000000000000000  x2   0000000000000000  x3   0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x8   0000000000000000  x9   0000000000000000  x10  0000000000000000  x11  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x12  0000000000000000  x13  0000000000000000  x14  0000000000000000  x15  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x16  0000000000000000  x17  0000000000000000  x18  000071bbcfb0c000  x19  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x20  0000000000000000  x21  0000000000000000  x22  0000000000000000  x23  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x24  0000000000000000  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     x28  0000000000000000  x29  0000000000000000  x30  0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   :     sp   000071bc26a8cff0  pc   0000000000000000  pstate 0000000000000000
04-08 15:08:48.451  4554  4560 E CRASH   : 
04-08 15:08:48.451  4554  4560 E CRASH   : backtrace:
04-08 15:08:48.458  4522  4537 I Finsky:quick_launch: [39] mst.run(21): Stats for Executor: LightweightExecutor ncj@2d8660e[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
04-08 15:08:48.460  4522  4537 I Finsky:quick_launch: [39] mst.run(21): Stats for Executor: BlockingExecutor ncj@20fe82f[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
04-08 15:08:48.464  4554  4554 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000000000008
04-08 15:08:48.464  4554  4554 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-08 15:08:48.464  4554  4554 E CRASH   : Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
04-08 15:08:48.464  4554  4554 E CRASH   : Build fingerprint: 'google/zork/zork_cheets:11/R112-15359.45.0/9844704:user/release-keys'
04-08 15:08:48.464  4554  4554 E CRASH   : Revision: '0'
04-08 15:08:48.464  4554  4554 E CRASH   : pid: 4554, tid: 4554, name: league.wildrift  >>> com.riotgames.league.wildrift <<<
04-08 15:08:48.464  4554  4554 E CRASH   :     x0   000071bc80e03ff5  x1   000000000009e77e  x2   000000000000000c  x3   0000000000000000
04-08 15:08:48.464  4554  4554 E CRASH   :     x4   0000000000000080  x5   732e6c6462696c00  x6   806c6962646c2e73  x7   722d6b6361686aff
04-08 15:08:48.464  4554  4554 E CRASH   :     x8   000000000000000c  x9   0000000000000000  x10  0000000000000005  x11  0000000000000008
04-08 15:08:48.464  4554  4554 E CRASH   :     x12  00000000ffffff83  x13  0000000000000008  x14  0000000000000000  x15  0000000079cfd502
04-08 15:08:48.464  4554  4554 E CRASH   :     x16  00000000fffeff3f  x17  000071bcce6eb100  x18  000071bc80e01540  x19  0000000000000000
04-08 15:08:48.464  4554  4554 E CRASH   :     x20  000071bc80e03ff5  x21  000071bc80e03f80  x22  0000000000000000  x23  0000000000000000
04-08 15:08:48.464  4554  4554 E CRASH   :     x24  0000000000000000  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-08 15:08:48.464  4554  4554 E CRASH   :     x28  0000000000000000  x29  000071bc80e03fc0  x30  000071bc26ce32ec
04-08 15:08:48.464  4554  4554 E CRASH   :     sp   000071bc80e03f80  pc   000071bc26cd74bc  pstate 0000000000000000
04-08 15:08:48.464  4554  4554 E CRASH   : 
04-08 15:08:48.464  4554  4554 E CRASH   : backtrace:
04-08 15:08:48.482  4554  4560 E CRASH   :      #00  pc 00000000005f66e8  /data/app/~~HKrXW1hhcKOmPfjAK6KodQ==/com.riotgames.league.wildrift-ESxFyLe7sMK3jYzunoSZYw==/lib/arm64/libunity.so ()
04-08 15:08:48.482  4554  4560 E CRASH   :      #01  pc 0000000000346380  /data/app/~~HKrXW1hhcKOmPfjAK6KodQ==/com.riotgames.league.wildrift-ESxFyLe7sMK3jYzunoSZYw==/lib/arm64/libunity.so ()
04-08 15:08:48.482  4554  4560 E CRASH   :      #02  pc 0000000000001018  /system/lib64/arm64/libnative_bridge_vdso.so ()
04-08 15:08:48.498  4554  4554 E CRASH   :      #00  pc 00000000005f66e8  /data/app/~~HKrXW1hhcKOmPfjAK6KodQ==/com.riotgames.league.wildrift-ESxFyLe7sMK3jYzunoSZYw==/lib/arm64/libunity.so ()
04-08 15:08:48.498  4554  4554 E CRASH   :      #01  pc 0000000000346380  /data/app/~~HKrXW1hhcKOmPfjAK6KodQ==/com.riotgames.league.wildrift-ESxFyLe7sMK3jYzunoSZYw==/lib/arm64/libunity.so ()
04-08 15:08:48.498  4554  4554 E CRASH   :      #02  pc 0000000000001018  /system/lib64/arm64/libnative_bridge_vdso.so ()
04-08 15:08:49.048   220   230 I ArcvmPowerService: CPU throttling is active
04-08 15:08:46.441   382   396 I ArcWifiService: getConnectionInfo() uid=10078 (com.riotgames.league.wildrift)
04-08 15:08:49.050   531  3559 I ArcWindowController: taskOcclusionChanged: taskId=17, occlusionFraction=1.0, reason=1
04-08 15:08:49.051   382   396 D ArcWindowManagerService: Activity cannot enter PIP mode, skipping request to enter PIP
04-08 15:08:49.051   531   531 I ArcWindowController: Launching chrome placeholder
04-08 15:08:49.052   382   396 I ActivityTaskManager: START u0 {act=org.chromium.arc.applauncher.PlaceholderActivity flg=0x10840000 cmp=org.chromium.arc.applauncher/.PlaceholderActivity} from uid 10041
04-08 15:08:49.052   382   400 D EventSequenceValidator: inc AccIntentStartedEvents to 2
04-08 15:08:49.053   382   476 E ArcGfxMetrics: Failed to find pattern in output: Total frames rendered: (\d+).
04-08 15:08:49.056   963   963 D ArcPlaceholder: New intent received: Intent { act=org.chromium.arc.applauncher.PlaceholderActivity flg=0x10c40000 cmp=org.chromium.arc.applauncher/.PlaceholderActivity }
04-08 15:08:49.056   963   963 E ArcPlaceholder: Ignoring unexpected Intent: Intent { act=org.chromium.arc.applauncher.PlaceholderActivity flg=0x10c40000 cmp=org.chromium.arc.applauncher/.PlaceholderActivity }
04-08 15:08:49.057   963   963 D ArcAppTaskTracker: Calculating task stack diff.
04-08 15:08:49.065   382   400 D EventSequenceValidator: dec AccIntentStartedEvents to 1
04-08 15:08:49.066   963   963 D ArcAppTaskTracker: Active task: 17.
04-08 15:08:49.066   382   400 I ActivityManager: Killing 1042:com.android.externalstorage/u0a25 (adj 985): empty #17
04-08 15:08:49.066   382   400 I ActivityManager: PendingStartActivityUids startActivity to updateOomAdj delay:2701ms, uid:10078
04-08 15:08:49.081   211   211 I Zygote  : Process 1042 exited due to signal 9 (Killed)
04-08 15:08:49.112   382   408 I libprocessgroup: Successfully killed process cgroup uid 10025 pid 1042 in 45ms
04-08 15:08:49.457   382   852 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
04-08 15:08:49.553   382   400 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{9b65808 u0 com.riotgames.league.wildrift/com.riotgames.account.rso.android.SocialLoginActivity t17}
04-08 15:08:50.301  4554  4606 E CRASH   : other thread is trapped; signum = 11
04-08 15:08:50.301  4554  4606 E AndroidRuntime: FATAL EXCEPTION: Timer-0
04-08 15:08:50.301  4554  4606 E AndroidRuntime: Process: com.riotgames.league.wildrift, PID: 4554
04-08 15:08:50.301  4554  4606 E AndroidRuntime: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000000000008
04-08 15:08:50.301  4554  4606 E AndroidRuntime: Build fingerprint: 'google/zork/zork_cheets:11/R112-15359.45.0/9844704:user/release-keys'
04-08 15:08:50.301  4554  4606 E AndroidRuntime: Revision: '0'
04-08 15:08:50.301  4554  4606 E AndroidRuntime: pid: 4554, tid: 4554, name: league.wildrift  >>> com.riotgames.league.wildrift <<<
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x0   000071bc80e03ff5  x1   000000000009e77e  x2   000000000000000c  x3   0000000000000000
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x4   0000000000000080  x5   732e6c6462696c00  x6   806c6962646c2e73  x7   722d6b6361686aff
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x8   000000000000000c  x9   0000000000000000  x10  0000000000000005  x11  0000000000000008
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x12  00000000ffffff83  x13  0000000000000008  x14  0000000000000000  x15  0000000079cfd502
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x16  00000000fffeff3f  x17  000071bcce6eb100  x18  000071bc80e01540  x19  0000000000000000
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x20  000071bc80e03ff5  x21  000071bc80e03f80  x22  0000000000000000  x23  0000000000000000
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x24  0000000000000000  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     x28  0000000000000000  x29  000071bc80e03fc0  x30  000071bc26ce32ec
04-08 15:08:50.301  4554  4606 E AndroidRuntime:     sp   000071bc80e03f80  pc   000071bc26cd74bc  pstate 0000000000000000
04-08 15:08:50.301  4554  4606 E AndroidRuntime: 
04-08 15:08:50.301  4554  4606 E AndroidRuntime:        at libunity.(:0)
04-08 15:08:50.301  4554  4606 E AndroidRuntime:        at libunity.(:0)
04-08 15:08:50.301  4554  4606 E AndroidRuntime:        at libnative_bridge_vdso.(:0)
04-08 15:08:50.307  4554  4606 E CrashReportSight: [Start]Calling 'onCrashHandleStart' of Bugly crash listener.
04-08 15:08:50.366  4554  4606 E CrashReportSight: [End]Calling 'onCrashHandleStart' of Bugly crash listener.
04-08 15:08:50.580  4554  4947 I CrashReportSight: deleteMemoryRecords
04-08 15:08:51.278  4554  4951 W System.err: javax.net.ssl.SSLPeerUnverifiedException: Hostname astat.bugly.cros.wr.pvp.net not verified:
04-08 15:08:51.278  4554  4951 W System.err:     certificate: sha1/QyGXHW+muBgFWxBQ+NC1eyLkTKA=
04-08 15:08:51.278  4554  4951 W System.err:     DN: C=US,ST=California,L=Los Angeles,O=Riot Games Inc,CN=android.bugly.wr.pvp.net
04-08 15:08:51.278  4554  4951 W System.err:     subjectAltNames: [android.bugly.wr.pvp.net, bugly.prod01.amer.cros.wr.pvp.net, api.bugly.prod01.amer.cros.wr.pvp.net, cas.bugly.prod01.amer.cros.wr.pvp.net, ios.bugly.prod01.amer.cros.wr.pvp.net, android.bugly.prod01.amer.cros.wr.pvp.net]
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
04-08 15:08:51.278  4554  4951 W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
04-08 15:08:51.278  4554  4951 W System.err:    at com.uqm.crashsight.proguard.g.a(:272)
04-08 15:08:51.278  4554  4951 W System.err:    at com.uqm.crashsight.proguard.g.a(:121)
04-08 15:08:51.278  4554  4951 W System.err:    at com.uqm.crashsight.proguard.j.run(:329)
04-08 15:08:51.278  4554  4951 W System.err:    at java.lang.Thread.run(Thread.java:923)
04-08 15:08:51.386   382   451 I WindowManager: Input event dispatching timed out sending to com.riotgames.league.wildrift/com.tencent.lolm.lgame.  Reason: e6d1ec2 com.riotgames.league.wildrift/com.tencent.lolm.lgame (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
04-08 15:08:51.404   382   451 D WindowManager: notifyANR took 18ms
04-08 15:08:51.404   382   451 W InputDispatcher: Canceling events for e6d1ec2 com.riotgames.league.wildrift/com.tencent.lolm.lgame (server) because it is unresponsive
04-08 15:08:51.412   382  4953 I ActivityManager: dumpStackTraces pids={608=true, 745=true, 819=true, 839=true, 860=true, 1103=true, 1120=true, 1175=true, 1234=true, 1609=true, 1745=true, 1801=true, 2193=true, 2841=true, 3100=true, 3348=true, 3446=true, 3604=true, 3894=true, 4246=true, 4401=true, 4452=true, 4522=true} nativepids=[134, 149, 189, 244, 245, 251, 253, 254, 257, 263, 276, 277, 839]
04-08 15:08:51.445   382   768 I ArcWifiService: getConnectionInfo() uid=10078 (com.riotgames.league.wildrift)
04-08 15:08:51.446   382   768 I ArcWifiService: getConnectionInfo() uid=10078 (com.riotgames.league.wildrift)
04-08 15:08:51.654   382  4953 I ActivityManager: Skipping next CPU consuming process, not a java proc: 4554
04-08 15:08:51.654   382  4953 I ActivityManager: Skipping next CPU consuming process, not a java proc: 382
04-08 15:08:51.666   382  4953 I ActivityManager: Dumping to /data/anr/anr_2023-04-08-15-08-51-658
04-08 15:08:51.666   382  4953 I ActivityManager: Collecting stacks for pid 4554
04-08 15:08:51.667   382  4953 I system_server: libdebuggerd_client: started dumping process 4554
04-08 15:08:51.668   172   172 I tombstoned: registered intercept for pid 4554 and type kDebuggerdJavaBacktrace
04-08 15:08:51.719   276   276 D BufferPoolAccessor2.0: bufferpool2 0x7c400fc17428 : 0(0 size) total buffers - 0(0 size) used buffers - 307/312 (recycle/alloc) - 8/312 (fetch/transfer)
04-08 15:08:51.719   276   276 D BufferPoolConnection: connection 1187091932741 closed on death
04-08 15:08:51.719   382   451 W InputDispatcher: channel 'e6d1ec2 com.riotgames.league.wildrift/com.tencent.lolm.lgame (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
04-08 15:08:51.719   382   451 E InputDispatcher: channel 'e6d1ec2 com.riotgames.league.wildrift/com.tencent.lolm.lgame (server)' ~ Channel is unrecoverably broken and will be disposed!
04-08 15:08:51.721   276   606 D BufferPoolAccessor2.0: bufferpool2 0x7c400fc17628 : 0(0 size) total buffers - 0(0 size) used buffers - 100/103 (recycle/alloc) - 3/103 (fetch/transfer)
04-08 15:08:51.721   276   606 D BufferPoolAccessor2.0: Destruction - bufferpool2 0x7c400fc17628 cached: 0/0M, 0/0% in use; allocs: 103, 97% recycled; transfers: 103, 97% unfetched
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c460) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c4d0) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c620) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c700) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c7e0) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c8c0) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2c9a0) has residual remoteRefcount 1
04-08 15:08:51.722   251   665 E MediaBufferGroup: buffer(0x7807a4c2ca80) has residual remoteRefcount 1
04-08 15:08:51.722   382  2216 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10078 AdministratorUids: [] RequestorUid: 10078 RequestorPackageName: com.riotgames.league.wildrift] ], android.os.BinderProxy@97c9cec)
04-08 15:08:51.722   382  2216 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=45, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10078 AdministratorUids: [] RequestorUid: 10078 RequestorPackageName: com.riotgames.league.wildrift] ], android.os.BinderProxy@c66e8b5)
04-08 15:08:51.723   382   508 I ActivityManager: Process com.riotgames.league.wildrift (pid 4554) has died: vis+3 TOP 
04-08 15:08:51.723   254   622 E mediaserver: unlinkToDeath: removed reference to death recipient but unlink failed.
04-08 15:08:51.723   254   622 E IPCThreadState: attemptIncStrongHandle(1): Not supported
04-08 15:08:51.723   382  1900 I WindowManager: WIN DEATH: Window{e6d1ec2 u0 com.riotgames.league.wildrift/com.tencent.lolm.lgame}
04-08 15:08:51.723   382  1900 W InputDispatcher: Attempted to unregister already unregistered input channel 'e6d1ec2 com.riotgames.league.wildrift/com.tencent.lolm.lgame (server)'
04-08 15:08:51.724   382   467 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=46, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10078 AdministratorUids: [] RequestorUid: 10078 RequestorPackageName: com.riotgames.league.wildrift] ] (release request)
04-08 15:08:51.724   382   467 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=45, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10078 AdministratorUids: [] RequestorUid: 10078 RequestorPackageName: com.riotgames.league.wildrift] ] (release request)
04-08 15:08:51.724   975   975 I AutoDuckingHelper: onPlaybackConfigChanged
04-08 15:08:51.724   975   975 I AutoDuckingHelper: getDuckedPlayers
